# Generated by Django 4.1.1 on 2022-10-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngo",
            name="registration_number",
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
